### ISSUE TITLE
How to build from source on MSYS2?

### ISSUE THREAD

**Issue by hgntn** [RandyGaul/cute_framework#104]
I'm using the MINGW64 environment.

**Comment by RandyGaul** [comment]
Hi there, I have very little experience with MSYS2. It looks like you can generate an MSYS2 makefile setup with CMake: https://www.msys2.org/docs/cmake/

The command looks like `-G "MSYS Makefiles"`, if you follow along [here](https://github.com/RandyGaul/cute_framework_project_template/blob/main/README.md#cmake-101-walkthrough) then step 7 would be this command.

**Comment by RandyGaul** [comment]
Feel free to re-open this or respond if you need more help or have more questions!
