### ISSUE TITLE
Swap in unit test harness pico_unit.h

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/cute_framework#114]
https://github.com/empyreanx/pico_headers/blob/main/pico_unit.h

**Comment by Condzi** [comment]
Basically, steps are as follows:
- [ ] add poco_test
- [ ] adapt the tests file-by-file
- [ ] remove test/test_harness.h

Tests should follow these example implementations:
https://github.com/empyreanx/pico_headers/tree/main/tests_pico_math 
https://github.com/empyreanx/pico_headers/blob/main/tests_pico_b64/main.c
