### ISSUE TITLE
Is the license of cute framework the same as cute headers? 

### ISSUE THREAD

**Issue by MetalMaxMX** [RandyGaul/cute_framework#152]
Hello! I am putting out this issue just to know something in specific. According to another repository and file (see https://github.com/RandyGaul/cute_headers/blob/master/cute_c2.h), the cute headers are dual-licensed with zlib and unlicensed public domain. I checked the Cute Framework files and it seems to be zlib-licensed only, is that the case then? Just wanted some clarification on this topic. Thank you and awesome work on this framework. 

Cheers!
MetalMaxMX

**Comment by RandyGaul** [comment]
I'm happy to also add public domain as well, if you're interested perhaps a PR to update the licenses?

**Comment by MetalMaxMX** [comment]
> I'm happy to also add public domain as well, if you're interested perhaps a PR to update the licenses?

Would this be fine? https://github.com/RandyGaul/cute_framework/pull/153

**Comment by RandyGaul** [comment]
Yep that works! There's also license in each source file, but, I think it'd be easier to modify the source files to say look in LICENSE.txt for licensing info. This can be done another time (or if you're concerned you can certainly submit a PR).

**Comment by MetalMaxMX** [comment]
Hello! I've got to it https://github.com/RandyGaul/cute_framework/pull/154
