### ISSUE TITLE
Expose internal functions to work with spritesheets

### ISSUE THREAD

**Issue by dandersch** [RandyGaul/cute_framework#165]
It would be useful to have something like `spritebatch_register_premade_atlas(...)` from `cute_spritebatch.h` as part of
this API in order to work with offline texture atlases, e.g. to use a spritesheet without having to manually split it up.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/commit/a453dcc91d1101d3914f03f37fe3ca3f2e9e65ef

The vast majority of the code for this feature was already implemented and tested, and simply needs wrappings in CF. This commit implements those wrappings. I haven't actually tested this code (yet), but it's likely to work. Please let me know if you have problems!
