### ISSUE TITLE
Memory leaks in macOS + Metal.

### ISSUE THREAD

**Issue by pusewicz** [RandyGaul/cute_framework#169]
Running any sample on macOS (ARM) with the Metal renderer causes memory to leak, 10-20mb/s for full-throttle, max-FPS samples.

<img width="1942" alt="image" src="https://github.com/user-attachments/assets/1cba1c35-32e7-4c7b-909c-ce3f39c987f7">

**Comment by RandyGaul** [comment]
This is confirmed a non-issue in the GPU branch, which will be merged in sometime soon to main. Closing this out for now as such :)
