### ISSUE TITLE
gpu: Apple silicon requires CUTE_SOUND_SCALAR_MODE

### ISSUE THREAD

**Issue by pusewicz** [RandyGaul/cute_framework#188]
For the `gpu` branch, when building `cute`, Apple silicon get the error:

```
In file included from /Users/piotr/Work/GitHub/cute_framework/src/cute_audio.cpp:27:
In file included from /Users/piotr/Work/GitHub/cute_framework/libraries/cute/cute_sound.h:748:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
```

Defining `CUTE_SOUND_SCALAR_MODE` fixes the issue.

**Comment by RandyGaul** [comment]
Thanks! Perhaps I’ll just add in a simd port for M2. I think my macOS box has an M2 processor I can test with.

**Comment by RandyGaul** [comment]
Should be fixed! At least, it builds. I still need to confirm if the NEON port actually works. Will do that soon, but closing this for now :)
