### ISSUE TITLE
Add option to build a library rather than framework on Apple

### ISSUE THREAD

**Issue by pusewicz** [RandyGaul/cute_framework#203]
For Apple devices, we always build the library as `cute.framework` which I don't think is necessary.

SDL3 gives you an option to pick, with the default being off: https://github.com/libsdl-org/SDL/blob/940f7535ef28cf663752d532756e2cb54f0342fc/CMakeLists.txt#L245

Something similar should be done for Cute.

**Comment by RandyGaul** [comment]
I’m happy to explore this. Do you have any suggestions or PR on altering the cmake build setup?
