### ISSUE TITLE
Consider swapping to macros for small functions

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/cute_framework#231]
A lot of smaller functions, especially math functions, may be best changed to macros to force code inline, which would give a boost in perf for debug mode.

**Comment by jonstvns** [comment]
Instead of macros, could you use `__forceinline` and `__attribute__((always_inline)) `?

If you switch to macros for math functions, I wouldn't be able to use `_Generic` since macro arguments don't have any types to match
```
#define len_sq(a) _Generic((a), \
    v2: cf_len_sq, \
    cpv2: cpvlengthsq \
)(a)
```

**Comment by pusewicz** [comment]
I think in general it would be nice to use `_Generic` to simplify the API.
