### ISSUE TITLE
online document

### ISSUE THREAD

**Issue by chunqian** [RandyGaul/cute_framework#30]
Hi RandyGaul
  I created online documentation for cute_framework, using docsify.js, and customized the theme, and it looks pretty good,
The cute_framework doc online address is [here](https://chunqian.github.io/#/cute_framework/), if you think it's ok, I'll be happy to pull request

**Comment by RandyGaul** [comment]
Wow these look really nice! I think it's super cool. I have some questions!

* How does github io work? Do the web pages sit in this repository here, but viewable on io?
* What are the steps to generate all the web pages? What dependencies must be installed to do it (if any)?
* When one of the docs is edited, how can the web pages be regenerated? Hopefully it is just a single button press or automated or something dead easy

**Comment by chunqian** [comment]
Docsify.js is non-intrusive and smartly loads your markdown pages, Just put the necessary files into the docs folder

**Comment by chunqian** [comment]
Docsify.js is non-intrusive and smartly loads your markdown pages

How does github io work? 
Use GitHub Pages, Settings -> Pages
<img width="948" alt="屏幕快照 2021-07-27 07 36 29" src="https://user-images.githubusercontent.com/13447930/127072530-26b42911-b09b-46f3-af17-4e7c9ad56b78.png">
rename doc to docs, choose docs

Do the web pages sit in this repository here, but viewable on io?
Yes, the web pages sit in this repository

What are the steps to generate all the web pages?
Just put the necessary files into the docs folder.
<img width="784" alt="屏幕快照 2021-07-27 07 40 36" src="https://user-images.githubusercontent.com/13447930/127072801-05a72486-9814-40b7-bc57-f5160ef3af3b.png">

What dependencies must be installed to do it (if any)?
No more

When one of the docs is edited, how can the web pages be regenerated?
After editing then push and refresh github.io/cute_framework

**Comment by chunqian** [comment]
I mainly customized the mariana theme, [mariana theme](https://github.com/chunqian/Theme-Mariana) is the only one I use, it's really eye friendly to program or read the documentation for a long time
Then when rendering with docsify, I did some redirection of links in markdown
<img width="890" alt="屏幕快照 2021-07-27 07 53 56" src="https://user-images.githubusercontent.com/13447930/127073716-5c78ba15-50ac-420c-ab7b-2010aa1c7327.png">

**Comment by RandyGaul** [comment]
For the link redirection, where does that javascript screenshot you posted go/run?

**Comment by RandyGaul** [comment]
Also please do a pull request, would be nice to figure out how to get these docs going and stuff

**Comment by chunqian** [comment]
Ok, I have submitted a pull request.

**Comment by RandyGaul** [comment]
Okay wow very interesting, so that regex is inside the .html file.

To update the website after I alter the source.md files, what do I need to do? Anything or is it automatic?

**Comment by chunqian** [comment]
just push, is it automatic.
if new module, edit _sidebar.md

**Comment by chunqian** [comment]
in README.md you need changed
https://randygaul.github.io/cute_framework/#/app to https://randygaul.github.io/cute_framework/#/app/
https://randygaul.github.io/cute_framework/#/app render app.md
https://randygaul.github.io/cute_framework/#/app/ Render app/README.md
