### ISSUE TITLE
Improve docs on how to use png_cache

### ISSUE THREAD

**Issue by ghost** [RandyGaul/cute_framework#40]
The docs are unclear that in order to draw stuff using a png_cache, you must call `make_batch(png_cache_get_pixels_fn(my_png_cache), my_png_cache)` create a custom `batch_t`.

If you fail to create the custom batcher and just use `sprite_get_batch()` like I did, you'll get an error in the console when attempting to draw a sprite inside a `png_cache_t`. The error is "Aseprite cache -- unable to find id <img_id>"

**Comment by RandyGaul** [comment]
Relevant https://github.com/RandyGaul/cute_framework/issues/35

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/commit/8d0a70606c1084ac37c9040285d39839dd40282d
