### ISSUE TITLE
Upgrade the mbedtls version to fix build error

### ISSUE THREAD

**Issue by linkzzy** [RandyGaul/cute_framework#48]
Try to building cute_framework on my macOS 12.4,the 3.0 version mbedtls will make "parameter 'output_size' set but not used" error,upgrade to the newer 3.1 will fix it(set GIT_TAG to v3.1.0).

**Comment by RandyGaul** [comment]
Cool! Thanks so much! If you submit a PR I can merge it from my phone. Instructions here to do it all form browser: https://t.co/ftnr4uQzsB

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/pull/49
