### ISSUE TITLE
Memory Bounds

### ISSUE THREAD

**Issue by irlanrobson** [RandyGaul/cute_framework#62]
Hi Randy, my pointer math might be a little rusty, but shouldn't this line detect if memory is in [lo, hi] memory bounds?

https://github.com/RandyGaul/cute_framework/blob/master/src/cute_memory_pool.cpp#L97

My code for memory pool is similar to yours, but for inside memory bounds test in my code I use:

int stride = element_size > sizeof(void*) ? element_size : sizeof(void*);
int in_bounds = (uint8_t*)element >= arena && (uint8_t*)element + stride <= arena + arena_size;

**Comment by RandyGaul** [comment]
This is definitely a bug, thanks for catching it Irlan! I’ll fix this shortly unless you want to submit a PR

**Comment by irlanrobson** [comment]
You're welcome. Excelent project BTW! 

Sorry, my coding time is a little limited currently. 

Fortunately this is a tiny mistake and I am giving you a fix so maybe you can just apply it. I am not using your library so no need to rush!

I tested my version and it is working well!

**Comment by RandyGaul** [comment]
All good! Some people really like getting their name on the repo as a contributor so I always try to ask just in case, even for small fixes. Kind of like a way to say thank you 😊

**Comment by irlanrobson** [comment]
😃😃

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/commit/05b01df34de94aca1155ba5cdfeee880dd261aeb

**Comment by irlanrobson** [comment]
Ah nevermind, it seems that this test invalidates my reasoning:

(void*)element >= pool->arena 

Anyways I thought you could get simple tests as the one I first showed. Did you find any problem with the test I first showed?

**Comment by RandyGaul** [comment]
I don’t see any problems. Clamping element_size above void* size happens in the constructor already, and moving the stride across the equation is what made sense in my head as I wrote it

**Comment by irlanrobson** [comment]
element_size stores the unclamped size in the constructor!

**Comment by RandyGaul** [comment]
Oh I see! It needs a check for less than operator not just greater than. Nice catch!

**Comment by RandyGaul** [comment]
Something like this look ok? https://github.com/RandyGaul/cute_framework/blob/master/src/cute_memory_pool.cpp

**Comment by irlanrobson** [comment]
Exactly!

**Comment by irlanrobson** [comment]
There is still one catch. Not much of a problem though. In the alloc function the element size passed to malloc should ideally be the real element size. This is why I think it is better to compute the stride in the free function and element_size be the real element size.

**Comment by RandyGaul** [comment]
The internal free list requires each element to be at least void* size, so I’d prefer to go with storing the clamped element size.

**Comment by irlanrobson** [comment]
Yeah, I know. Both approaches are equally fine I guess. 🙂

**Comment by RandyGaul** [comment]
lmk if you catch anything else Irlan, here or on other files you might be looking at!

**Comment by irlanrobson** [comment]
Sure!!
