### ISSUE TITLE
Why not use metal backend in macos?

### ISSUE THREAD

**Issue by likun123687** [RandyGaul/cute_framework#86]
https://github.com/RandyGaul/cute_framework/blob/d48eebc8c1bf3764763b276f2283a37de4ec4789/include/cute_defines.h#L123
```
#if defined(CUTE_WINDOWS)
#	define SOKOL_D3D11
#elif defined(CUTE_LINUX)
#	define SOKOL_GLCORE33
#elif defined(CUTE_MACOSX)
#	define SOKOL_GLCORE33
#elif defined(CUTE_EMSCRIPTEN)
#	define SOKOL_GLES3
#	include <emscripten.h>
#endif
```

**Comment by RandyGaul** [comment]
Made some notes here about todo items in CF to unlock Metal https://github.com/RandyGaul/cute_framework/issues/87
